# Generated by Django 4.2.28 on 2026-02-10 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_passwordresettoken"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="passwordresettoken",
            new_name="password_re_token_060a1f_idx",
            old_name="password_re_token_c5e8e9_idx",
        ),
        migrations.RenameIndex(
            model_name="passwordresettoken",
            new_name="password_re_user_id_75c3a8_idx",
            old_name="password_re_user_id_e8f9a0_idx",
        ),
    ]
