# Generated by Django 4.2.28 on 2026-09-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_password_re_token_c5e8e9_idx_password_re_token_060a1f_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="about_me",
            field=models.TextField(blank=True, help_text="Extended information about the user.", verbose_name="about me"),
        ),
    ]
