# Generated by Django 4.2.28 on 2026-02-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="A short biography of the author.",
                        max_length=1000,
                        verbose_name="biography",
                    ),
                ),
                (
                    "avatar_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the author avatar image.",
                        max_length=500,
                        null=True,
                        verbose_name="avatar URL",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="Author personal website or portfolio.",
                        null=True,
                        verbose_name="website",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Author",
                "verbose_name_plural": "Authors",
                "db_table": "authors",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the blog post.",
                        max_length=200,
                        verbose_name="title",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version of the title.",
                        max_length=250,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The main content of the blog post.",
                        verbose_name="content",
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        blank=True,
                        help_text="A short summary of the post.",
                        max_length=500,
                        verbose_name="excerpt",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        db_index=True,
                        default="draft",
                        help_text="Publication status of the post.",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "featured_image_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the featured image for the post.",
                        max_length=500,
                        null=True,
                        verbose_name="featured image URL",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When the post was published.",
                        null=True,
                        verbose_name="published at",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
                "db_table": "blog_posts",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The comment content.",
                        max_length=2000,
                        verbose_name="content",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether the comment is approved for display.",
                        verbose_name="approved",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
                "db_table": "comments",
                "ordering": ["-created_at"],
            },
        ),
    ]
